---
api:
  url: https://fhir.sandboxcernerpowerchart.com/dstu2/d075cf8b-3261-481d-97e5-ba6c48d3b41f/
  patient: 1316024

auth:
  strategy: authorization_code
  steps:
    - find: "#j_username"
    - type: "ARGONAUT"
    - find: "#j_password"
    - type: "sprinttest"
    - find: "#loginButton"
    - click

  client_id: fedc3945-10a7-41bd-9aae-93e00ab9f9c4
  client_secret:
  scope: launch patient/Patient.read patient/Observation.read patient/Condition.read patient/MedicationOrder.read patient/MedicationStatement.read patient/MedicationDispense.read patient/MedicationAdministration.read patient/AllergyIntolerance.read patient/Procedure.read patient/Immunization.read patient/DocumentReference.read online_access
  extra_launch_params:
    launch: 8de5dad5-4e22-4b06-bde5-60f6a5781fd0

authorizer: !!python/name:testsuite.oauth.authorize.base.Authorizer
