---
api:
  url: https://open-ic.epic.com/Argonaut/api/FHIR/Argonaut/
  patient: Tbt3KuCY0B5PSrJvCu2j-PlK.aiHsu2xUjUM8bWpetXoB

auth:
  strategy: refresh_token
  client_id: dd24090e-bc30-4a18-8355-fa3664bff207
  client_secret:
  scope: launch/patient patient/*.read
