---
api:
  url: http://smart.dev.syncfor.science:9000/api/fhir/

auth:
  strategy: refresh_token
  client_id: test-client
  # client_secret intentionally included
  client_secret: 8e43d006-a25d-4786-8041-40473e4c097c
  scope: launch/patient patient/*.read offline_access
  confidential_client: True
  authorizer: !!python/name:testsuite.oauth.authorize.smart.SmartAuthorizer
