---
api:
  url: http://smart.dev.syncfor.science:9000/api/fhir/
  patient: smart-1288992

auth:
  username: demo
  password: demo
  client_id: test-suite
  client_secret: demo-secret-s4s
  scope: launch patient/*.read offline_access
  basic: yes
